services:
  app:
    build: .
    container_name: php-app
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - app-network

  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - app-network
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
  ###< doctrine/doctrine-bundle ###
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - app-network
    volumes:
      - "./rabbitmq/logs:/var/log/rabbitmq:rw"
    environment:
      RABBITMQ_DEFAULT_USER: app
      RABBITMQ_DEFAULT_PASS: '!ChangeMe!'
  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: php-nginx
    ports:
      - "8003:8003"
    volumes:
      - ./:/var/www/html:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
    links:
      - app
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###